name: Release
on:
  release: # https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  preflight:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: npm install
    - name: Test
      run: npm test
    - name: transpile
      run: npm run transpile
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: TranspiledSrc # optional
        # A file, directory or wildcard pattern that describes what to upload
        path: dist/*
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      with:
        # Artifact name
        name: TranspiledSrc
        # Destination path
        path: .
    - name: List artifacts
      run: ls

