name: Release
on:
  release: # https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release
    types: [created]
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: TRY ENV
        run: MYTAG=$(echo "v1.1.1")
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64, linux/arm64
          file: subfolder/Dockerfile
          push: true
          tags: iansegers/poc-githubactionbuild:$MYTAG
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
